<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Suggession Class Example_autocomplete</name>
   <tag></tag>
   <elementGuidId>9d0b4d49-cf97-43f6-a67d-075760132ad7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autocomplete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#autocomplete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>181d4b4a-1b11-40eb-8d2f-9dce3d560945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93d12770-b523-431c-9356-ce56d8b2cc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autocomplete</value>
      <webElementGuid>1da59c41-1b8f-48bf-b5a7-d3b59c9d73f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputs ui-autocomplete-input</value>
      <webElementGuid>82695334-af4b-49a7-af8b-2abb3ede7292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type to Select Countries</value>
      <webElementGuid>de507cf5-86e7-4588-a584-27ea6575b0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0832da89-a449-4ff2-b2e0-51b6552025d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autocomplete&quot;)</value>
      <webElementGuid>d7bed6b1-bc0c-4625-bae3-67b01e8f4798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autocomplete']</value>
      <webElementGuid>ed6512bd-c825-475e-889b-707456351087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-class-example']/fieldset/input</value>
      <webElementGuid>b1cd4890-fb0a-4751-9341-49e5a33bf841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>2475c538-0c5b-4370-becc-c91b498c90ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'autocomplete' and @placeholder = 'Type to Select Countries']</value>
      <webElementGuid>7e2239ec-a3f2-464a-bbf8-86b81adfc784</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
