<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select                     Option1  _bf898a</name>
   <tag></tag>
   <elementGuidId>d486bb49-d48d-45af-90c4-7529182e5048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dropdown-class-example']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdown-class-example</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0bbe10c9-7a54-47aa-95d0-0359cf66000d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdown-class-example</value>
      <webElementGuid>3da7038d-afff-495f-a3ad-e917a48b70b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dropdown-class-example</value>
      <webElementGuid>81d80ddb-bdcd-4d57-b5dc-64370466f0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                     Select
                     Option1
                    Option2
                    Option3
                </value>
      <webElementGuid>e1585be6-dcfa-4bd4-900a-e79aa54281c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-class-example&quot;)</value>
      <webElementGuid>322a4940-e6bc-4bd0-a3d1-fa56f2dd830d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dropdown-class-example']</value>
      <webElementGuid>8e868dc8-048d-4cbb-a409-15c59813da6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown Example'])[1]/following::select[1]</value>
      <webElementGuid>a29228fd-54fc-4ae4-b5ec-93aacda19372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggession Class Example'])[1]/following::select[1]</value>
      <webElementGuid>41fe57fc-9925-45b3-bcb2-c7e1cda44b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkbox Example'])[1]/preceding::select[1]</value>
      <webElementGuid>5cfea5b7-91f3-4e62-b042-ee1f77a5e3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b94527fa-a5d6-4d90-9bd8-3489cb65fb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dropdown-class-example' and @name = 'dropdown-class-example' and (text() = '
                     Select
                     Option1
                    Option2
                    Option3
                ' or . = '
                     Select
                     Option1
                    Option2
                    Option3
                ')]</value>
      <webElementGuid>0a6fb90f-144f-4573-8a26-8a4ab3152a18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
