<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Go Back_ws-back</name>
   <tag></tag>
   <elementGuidId>d1892420-7a06-415f-b955-028a5afbc3e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ws-back']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ws-back&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b79ab15a-82fe-47f4-ac48-e04affc7e889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>025fbe26-dcc8-48f0-a282-936feb4ff1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>       Go Back       </value>
      <webElementGuid>0483fed5-fde0-4a92-bb71-db1390a4a1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>parent.history.back()</value>
      <webElementGuid>23c88647-2d2f-4354-8cbb-aaa3f046b9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ws-back</value>
      <webElementGuid>74768f3a-8f0a-430d-89de-fddac8175ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;options&quot;)/form[@class=&quot;option&quot;]/p[1]/input[1]</value>
      <webElementGuid>910f1796-d18a-46ad-ac58-c876ab783d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/frames/Page_Practice Page/iframe_iFrame Example_iframe-name</value>
      <webElementGuid>039fcd52-8eb3-4988-a36b-2cf1909535d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ws-back']</value>
      <webElementGuid>daaa67cd-577b-440f-a334-d29965aa5e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='options']/form/p/input</value>
      <webElementGuid>f10b0e41-bd57-419f-8b2f-dbc3c0e901b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6183303c-7302-475b-9fe4-d95651e6b901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'ws-back']</value>
      <webElementGuid>950d51c6-7723-4465-be84-03a5f8d5e3de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
